apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: projet-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Molka-Kbaier/projetpfe-deployement.git'
    targetRevision: main
    path: manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: projet-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

